apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: database
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: wp-db
  MYSQL_USER: wp-db-user
  MYSQL_PASSWORD: asdadas

