# This is a basic workflow to help you get started with Actions

name: buid-images-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '*/Dockerfile'

jobs:

  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep Dockerfile | xargs )"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push images
        run: |
          for path in ${{ steps.getfile.outputs.files }}
          do
            pwd
            tag="l9xhub/"`echo $path | awk -F "/" '{print $1}'`":latest";
            docker build -t $tag ./$path
          done

