name: Deploy to Amazon EKS

on:
  push:
    branches:
      - deploy
env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
      
    - name: KUBE_CONFIG setup
      run: |
        echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > /tmp/config
        export KUBECONFIG=/tmp/config
        kubectl get nodes
