name: Deploy to Amazon EKS

on:
  push:
    branches:
      - deploy
env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: KUBE_CONFIG setup
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > /tmp/config
        KUBECONFIG=/tmp/config
        kubectl --help
