name: 'Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: main

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout git
      uses: actions/checkout@v2
    
    - name: Check terra
      run: terraform --version
