name: 'Terraform-Apply'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform-Apply'
    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    # Checkout git current git repository
    - name: Checkout git
      uses: actions/checkout@v2
      
    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
         
    # Check connection to AWS
    - name: Check connection to AWS
      run: aws sts get-caller-identity

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -var-file prod.tfvars

    # Change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply -var-file prod.tfvars -auto-approve
    
    - name: Update KUBE_CONFIG_DATA_STAGING
      run: |
        login="skiyl9x"
        github_token=${{ secrets.PERSONAL_GITHUB_TOKEN }}
        secret_name="KUBE_CONFIG_DATA_STAGING"
        repository="DevOps-CC21-demo"
        filename="kubeconfig"
        
        aws eks --region $(terraform output -raw region) \
                  update-kubeconfig \
                  --name $(terraform output -raw cluster_name) \
                  --kubeconfig $filename
                  
        wget https://raw.githubusercontent.com/skiyl9x/git_hub_secrets/main/git_secret.py
        
        python3 git_secret.py --lg=$login \
                              --tk=$github_token \
                              --sn=$secret_name \
                              --repo=$repository \
                              --filename=$filename
