name: 'Terraform'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    # Checkout git current git repository
    - name: Checkout git
      uses: actions/checkout@v2
      
    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
         
    # Check connection to AWS
    - name: Check connection to AWS
      run: aws sts get-caller-identity

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -var-file prod.tfvars

    # Change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform destroy -var-file prod.tfvars -auto-approve
