name: Test

on:
  workflow_dispatch:
    
env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update kubectl
      run: echo ${{ secrets.VAULT_KEYS }}
      
