name: Create/update_credentials_in_vault

on:
 
  workflow_run:
    workflows: [Deploy_vault]
    types: [completed]
    branches: [deploy]
  workflow_dispatch:
    
env:
  AWS_REGION: us-east-2


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run:
        shell: bash
        working-directory: vault

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
      

    - name: Generate new db key in vault
      uses: skiyl9x/helm-eks-action@master
      env:
            KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
            VAULT_KEYS: ${{ secrets.VAULT_KEYS }}
      with:
          command: |
                  curl -q -o vault_add_new_key_k8s.sh https://raw.githubusercontent.com/skiyl9x/vault-k8s/main/vault_add_new_key_k8s.sh
                  chmod +x vault_add_new_key_k8s.sh
                  ./vault_add_new_key_k8s.sh all_steps